### ISSUE TITLE
Página para exibição individual de uma Publicação

### ISSUE THREAD

**Issue by ghost** [ancaphub/ancaphub#3]
A página para exibição individual de uma postagem deverá fazer o fetch da postagem em questão e exibir-la  com o  componente **PostCard** ( _client/src/components/posts/postCard.jsx_). 

Seu link deve ser algo como _/[remetente]/[id do remetente]/[id da postagem]_, sendo o remetente da postagem o local onde ela foi feita, podendo ser **user** (caso seja feita em um perfil) ou **group** (caso seja feita em um grupo).

**Comment by luismanfroni** [comment]
"...[remetente]/[id do remetente]..."
você quis dizer [destinatario]/[id do remetente]?
